spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/louie
    username: louie
    password: louie1234
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true